apiVersion: v1
kind: Namespace
metadata:
  name: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 423224728550.dkr.ecr.ap-south-1.amazonaws.com/ca-diy-service:latest   # Back-end docker image 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#  name: backend
# spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: backend
#  minReplicas: 1
#  maxReplicas: 10
#  targetCPUUtilizationPercentage: 70
---

