apiVersion: v1
kind: Namespace
metadata:
  name: nk-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk-test
  namespace: nk-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nk-test
  template:
    metadata:
      labels:
        app: nk-test
    spec:
      containers:
      - name: nk-test
        image: 423224728550.dkr.ecr.ap-south-1.amazonaws.com/cadiy-uat-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nk-test-svc
  namespace: nk-test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nk-test
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nk-test-ingress
  namespace: nk-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  host: testuat.aubankuat.in
  rules:
  - http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: nk-test-svc
          port:
            number: 80
